"""Shell completion scripts for relay — generated from one data table.

Shipping completions as a ``relay completions <shell>`` command (instead of
static files that drift from the CLI) guarantees the tab-completion words always
match the installed binary's actual subcommands and flags.

Supported shells:
    bash, zsh, fish, powershell

Usage:
    relay completions bash           # print to stdout
    relay completions bash > ~/.bash_completion.d/relay
    relay completions zsh > "${fpath[1]}/_relay"
    relay completions fish > ~/.config/fish/completions/relay.fish
    relay completions powershell > relay-completion.ps1
"""
from __future__ import annotations

# The single source of truth for what the completion scripts advertise. Kept in
# sync with the argparse definitions in relay/cli.py; order does not matter for
# any shell, but grouping keeps the generators readable.
SUBCOMMANDS = [
    "amend", "completions", "doctor", "man", "pr", "squash", "stage",
    "telemetry", "undo",
]

GLOBAL_FLAGS = [
    "--version", "--solo", "--team", "--provider", "--timeout",
    "--yes", "--dry-run", "--no-push", "--staged", "--no-verify",
    "--allow-protected", "--hunks", "--repo", "--verbose",
]

# One-line descriptions used by the fish generator. Fish takes a -a <name>
# token plus a -d <description>; keeping the map here (keyed by SUBCOMMANDS)
# preserves the helpful one-liners while the loop guarantees every subcommand
# is advertised.
_FISH_DESCRIPTIONS = {
    "amend": "rewrite the last commit message",
    "completions": "print a shell completion script",
    "doctor": "diagnose this install",
    "man": "print the relay(1) manual page",
    "pr": "open a pull request / merge request",
    "squash": "squash the last N commits",
    "stage": "interactively stage a subset of changed files",
    "telemetry": "view or change opt-in usage telemetry",
    "undo": "undo the last commit",
}

SHELLS = ("bash", "zsh", "fish", "powershell")


def _bash_list() -> str:
    return " ".join(GLOBAL_FLAGS + list(SUBCOMMANDS))


def bash_script() -> str:
    opts = _bash_list()
    return f"""# bash completion for relay
# Generated by `relay completions bash`. Source this in your ~/.bashrc.
_relay_complete()
{{
    local cur prev
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{opts}" -- "$cur") )
        return 0
    fi
    if [[ "${{COMP_WORDS[1]}}" == completions ]]; then
        COMPREPLY=( $(compgen -W "bash zsh fish powershell" -- "$cur") )
        return 0
    fi
    if [[ "${{COMP_WORDS[1]}}" == pr ]]; then
        COMPREPLY=( $(compgen -W "--base --title --open --draft --yes --verbose" -- "$cur") )
        return 0
    fi
    COMPREPLY=( $(compgen -W "{opts}" -- "$cur") )
}}
complete -F _relay_complete relay
"""


def zsh_script() -> str:
    subs = " ".join(SUBCOMMANDS)
    return f"""#compdef relay
# Generated by relay completions zsh. Drop into $fpath as _relay.
_arguments \\
  '--solo[stage, commit and push to the current branch]' \\
  '--team=[create & checkout a feature branch]:feature' \\
  '--provider[AI provider]:provider:(anthropic gemini groq mistral ollama openai xai)' \\
  '--timeout[seconds to wait for the AI response]:seconds' \\
  '--yes[skip the confirmation prompt]' \\
  '--dry-run[show the plan; change nothing]' \\
  '--no-push[commit but do not push]' \\
  '--staged[only commit what is already staged]' \\
  '--no-verify[skip git pre-commit and commit-msg hooks]' \\
  '--allow-protected[allow team mode to target a protected branch]' \\
  '--hunks[generate multi-part AI message per file/hunk]' \\
  '--repo=[run on this repo path]:repo:_files -/' \\
  '--verbose[print the git commands being run]' \\
  '--version[print the relay version]' \\
  '1:subcommand:({subs})' \\
  '*::arg:->args'
"""


def fish_script() -> str:
    lines = [
        "# fish completion for relay",
        "# Generated by relay completions fish.",
        "complete -c relay -s h -l help -d 'Show help'",
    ]
    # Subcommand lines are generated from SUBCOMMANDS (single source of truth)
    # so a new subcommand can never be forgotten here, like bash/zsh/powershell.
    for subcommand in SUBCOMMANDS:
        lines.append(
            "complete -c relay -n '__fish_use_subcommand' "
            f"-a '{subcommand}' -d '{_FISH_DESCRIPTIONS[subcommand]}'"
        )
    lines += [
        "complete -c relay -n '__fish_use_subcommand' -l solo -d 'commit on the current branch'",
        "complete -c relay -n '__fish_use_subcommand' -l team -d 'create & checkout a feature branch'",
        "complete -c relay -n '__fish_use_subcommand' -l provider -x -a 'anthropic gemini groq mistral ollama openai xai' -d 'AI provider'",
        "complete -c relay -n '__fish_use_subcommand' -l timeout -x -d 'seconds to wait for the AI'",
        "complete -c relay -n '__fish_use_subcommand' -l yes -d 'skip the confirmation prompt'",
        "complete -c relay -n '__fish_use_subcommand' -l dry-run -d 'show the plan; change nothing'",
        "complete -c relay -n '__fish_use_subcommand' -l no-push -d 'commit but do not push'",
        "complete -c relay -n '__fish_use_subcommand' -l staged -d 'only commit what is staged'",
        "complete -c relay -n '__fish_use_subcommand' -l no-verify -d 'skip git hooks'",
        "complete -c relay -n '__fish_use_subcommand' -l allow-protected -d 'allow team mode to target a protected branch'",
        "complete -c relay -n '__fish_use_subcommand' -l hunks -d 'generate multi-part AI message per file/hunk'",
        "complete -c relay -n '__fish_use_subcommand' -l repo -r -d 'run on this repo path'",
        "complete -c relay -n '__fish_use_subcommand' -l verbose -d 'print the git commands'",
    ]
    return "\n".join(lines) + "\n"


def powershell_script() -> str:
    opts = " ".join(GLOBAL_FLAGS + list(SUBCOMMANDS))
    return f"""# PowerShell argument completer for relay
# Generated by relay completions powershell. Add to your $PROFILE:
#     . ``$PSScriptRoot/relay-completion.ps1``
Register-ArgumentCompleter -Native -CommandName relay -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)
    $terms = @("{opts}" -split ' ')
    $terms | Where-Object {{ $_ -like "$wordToComplete*" }} | Sort-Object -Unique |
        ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }}
}}
"""


def generate(shell: str) -> str:
    """Return the completion script for ``shell``; raises ValueError otherwise."""
    normalized = shell.lower()
    if normalized not in SHELLS:
        raise ValueError(
            f"unsupported shell '{shell}'; choose from: {', '.join(SHELLS)}"
        )
    return {
        "bash": bash_script,
        "zsh": zsh_script,
        "fish": fish_script,
        "powershell": powershell_script,
    }[normalized]()


__all__ = [
    "SUBCOMMANDS",
    "GLOBAL_FLAGS",
    "SHELLS",
    "generate",
]
